config/routes.rb
Probono::Application.routes.draw do

  get "comments/new"
  resources :maintenance_requests do
    resources :maintenance_comments, only: [:create, :destroy]
  end
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users

  resources :users
  
  match "contact" => 'welcome#contact', via: :get
  root :to => 'welcome#index'
  resources :cherrystreet, only: [:index]
  match "cherrystreet/floorplans" => 'cherrystreet#floorplans', via: :get
  match "cherrystreet/neighborhood" => 'cherrystreet#neighborhood', via: :get
  match "cherrystreet/pictures" => 'cherrystreet#pictures', via: :get
  
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.role? :tenant
      can :manage, MaintenanceRequest, apartment_id: user.apartment_id
      can :manage, MaintenanceComment, user_id: user.id
    end

    if user.role? :landlord
    end

    if user.role? :admin
      can :manage, :all
    end
    
  end
end

app/models/apartment.rb
class Apartment < ActiveRecord::Base
  belongs_to :building
  has_many :users
  has_many :maintenance_requests
  attr_accessible :unit, :bedrooms, :bathrooms, :floorplan, :image, :building_id, :user_ids

  validates :unit, presence: true
  validates :bedrooms, presence: true
  validates :bathrooms, presence: true
  validates :building, presence: true

  def apartment_label_method
    "#{self.building.name} #{self.unit}"
  end
end

app/models/building.rb
class Building < ActiveRecord::Base
  has_many :apartments
  attr_accessible :street, :city, :state, :zip, :name, :apartment_ids

  validates :street, length: { minimum: 2 }, presence: true
  validates :city, length: { minimum: 2 }, presence: true
  validates :state, length: { minimum: 2 }, presence: true
  validates :zip, length: { minimum: 5 }, presence: true
  validates :name, length: { minimum: 3 }, presence: true

end

app/models/concerns/filterable.rb
module Filterable
  extend ActiveSupport::Concern

  module ClassMethods
    def filter(filtering_params)
      results = self.where(nil)
      filtering_params.each do |key, value|
        results = results.public_send(key, value) if value.present?
      end
      results
    end
  end
end

app/models/maintenance_comment.rb
class MaintenanceComment < ActiveRecord::Base
  belongs_to :maintenance_request
  belongs_to :user

  attr_accessible :user, :comment
end

app/models/maintenance_request.rb
class MaintenanceRequest < ActiveRecord::Base
  include Filterable

  belongs_to :user
  belongs_to :apartment
  has_many :maintenance_comments
  scope :status, -> (status) { where status: status }

  attr_accessible :status, :priority, :description, :title, :email_updates, :user, :apartment

  validates :title, length: { minimum: 5 }, presence: true
  validates :description, length: { minimum: 20 }, presence: true
  validates :user, presence: true
  validates :apartment, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :maintenance_requests
  has_many :maintenance_comments
  belongs_to :apartment
  before_create :set_tenant

  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :approved, :apartment_validation, :role, :active, :emergency_contact_name, :emergency_contact_phone, :emergency_contact_relationship, :apartment_id, :apartment

  ROLES = %w[tenant landlord admin]

  def role?(base_role)
    role.nil? ? false : ROLES.index(base_role.to_s) <= ROLES.index(role)
  end

  def active_for_authentication?
    super && approved?
  end

  def inactive_message
    if !approved?
      :not_approved
    else  
      super
    end
  end

  def user_label_method
    "#{self.first_name} #{self.last_name}"
  end

  private 

  def set_tenant
    self.role = 'tenant'
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, :alert => exception.message
  end

  before_filter :update_sanitized_params, if: :devise_controller?
  def update_sanitized_params
    devise_parameter_sanitizer.for(:account_update) {|u| u.permit(:email, :first_name, :last_name, :password, :password_confirmation, :current_password, :approved, :apartment_validation, :role, :active)}
    devise_parameter_sanitizer.for(:sign_up) {|u| u.permit(:email, :first_name, :last_name, :password, :password_confirmation, :apartment_validation, :role, :approved)}
  end



end

app/controllers/cherrystreet_controller.rb
class CherrystreetController < ApplicationController
  def index
  end

  def floorplans
  end

  def neighborhood
  end

  def pictures
  end
end

app/controllers/maintenance_comments_controller.rb
class MaintenanceCommentsController < ApplicationController
  def create
    @mr = MaintenanceRequest.find(params[:maintenance_request_id])
    @comments = @mr.maintenance_comments
    @comment = current_user.maintenance_comments.build(params[:maintenance_comment])
    @comment.maintenance_request = @mr
    if @comment.save
      flash[:notice] = "Your comment was created."
      redirect_to @mr
    else
      flash[:error] = "There was an error creating your comment. Please try again."
      render 'maintenance_requests/show'
    end
  end
end

app/controllers/maintenance_requests_controller.rb
class MaintenanceRequestsController < ApplicationController

  def new
    @mr = MaintenanceRequest.new
    authorize! :create, MaintenanceRequest, message: "You must be logged in to create a maintenance request."
  end
  
  def create
    @mr = current_user.maintenance_requests.build(params[:maintenance_request])
    authorize! :create, MaintenanceRequest, message: "You must be logged in to create a maintenance request."
    @mr.status = "Open"
    @mr.apartment ||= current_user.apartment
    if @mr.save
      flash[:notice] = "You have submitted a maintenance request."
      redirect_to @mr
    else
      flash[:error] = "There was an error submitting your maintenance request. Please try again."
      render :new
    end
  end
  
  def index
    if current_user
      if current_user.role == "admin"
        @mainrequests = MaintenanceRequest.filter(params.slice(:status)).order("created_at ASC").paginate(:page => params[:page], :per_page => 10)
      elsif current_user.apartment == nil
        @mainrequests = nil
      else
        apt_user_ids = current_user.apartment.users.ids
        @mainrequests = MaintenanceRequest.filter(params.slice(:status)).where(user_id: apt_user_ids).order("created_at ASC").paginate(:page => params[:page], :per_page => 10)
      end
    end
    authorize! :read, MaintenanceRequest, message: "You must be logged in to view maintenance requests."
  end

  def show
    @mr = MaintenanceRequest.find(params[:id])
    authorize! :read, @mr, message: "You can only view maintenance requests associated to your apartment."
    @comments = @mr.maintenance_comments
    @comment = MaintenanceComment.new
  end
  
  def edit
    @mr = MaintenanceRequest.find(params[:id])
    authorize! :edit, @mr, message: "You can only view maintenance requests associated to your apartment."
  end

  def update
    @mr = MaintenanceRequest.find(params[:id])
    authorize! :update, @mr, message: "You can only view maintenance requests associated to your apartment."
    if @mr.update_attributes(params[:maintenance_request])
      flash[:notice] = "Your maintenance request has been updated."
      redirect_to @mr
    else
      flash[:error] = "There was an error updating your maintenance request. Please try again."
      render :edit
    end
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def control_group_tag(errors, &block)
    if errors.any?
      content_tag :div, capture(&block), class: 'control-group error'
    else
      content_tag :div, capture(&block), class: 'control-group'
    end
  end
  def comment_url_helper(comment)
    maintenance_request = comment.maintenance_request
    [maintenance_request, comment]
  end
end

app/helpers/cherrystreet_helper.rb
module CherrystreetHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/maintenance_requests_helper.rb
module MaintenanceRequestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cherrystreet/_navbar.html.erb
<div class="buildingnavbar">
  <%= link_to "Cherry Street", cherrystreet_index_path %> | 
  <%= link_to "Floorplans", cherrystreet_floorplans_path %> | 
  <%= link_to "Pictures", cherrystreet_pictures_path %> | 
  <%= link_to "Neighborhood", cherrystreet_neighborhood_path %>
</div>
<p></p>

app/views/cherrystreet/floorplans.html.erb
<div class="row">
  <div class="col-xs-12">
  <h1>Floor Plans and Pictures</h1>
    With both 1 and 2 bedroom floor plans, you will likely find a living situation that matches your lifestyle.
  </div>
  <div class="row">
    <div class="col-xs-5 col-xs-offset-1">
      <h2>1 Bedroom</h2>
      <p>Our one bedrooms average 500 square feet, each come with a kitchen that opens into an expansive living room.</p>

      <%= link_to image_tag("1bedroomoriginals/1brfloorplanoriginal.jpg", :class => 'bedroom-thumbs'), image_path("1bedroomoriginals/1brfloorplanoriginal.jpg"), :rel => 'fancybox-thumb1', :class =>"fancybox-thumb" %>
      <%= link_to image_tag("1bedroomoriginals/1brfloorplanoriginal.jpg", :class => 'bedroom-thumbs'), image_path("1bedroomoriginals/1brfloorplanoriginal.jpg"), :rel => 'fancybox-thumb1', :class =>"fancybox-thumb" %>
      <%= link_to image_tag("1bedroomoriginals/1brfloorplanoriginal.jpg", :class => 'bedroom-thumbs'), image_path("1bedroomoriginals/1brfloorplanoriginal.jpg"), :rel => 'fancybox-thumb1', :class =>"fancybox-thumb" %>
      <%= link_to image_tag("1bedroomoriginals/1brfloorplanoriginal.jpg", :class => 'bedroom-thumbs'), image_path("1bedroomoriginals/1brfloorplanoriginal.jpg"), :rel => 'fancybox-thumb1', :class =>"fancybox-thumb" %>
     </div>

    <div class="col-xs-5">
      <h2>2 Bedrooms</h2>
      <p>A majority of our apartments are beautiful 2 bedrooms withA majority of our apartments are beautiful 2 bedrooms with </p>

      <%= link_to image_tag("1bedroomoriginals/1brfloorplanoriginal.jpg", :class => 'bedroom-thumbs'), image_path("1bedroomoriginals/1brfloorplanoriginal.jpg"), :rel => 'fancybox-thumb2', :class =>"fancybox-thumb" %>
      <%= link_to image_tag("1bedroomoriginals/1brfloorplanoriginal.jpg", :class => 'bedroom-thumbs'), image_path("1bedroomoriginals/1brfloorplanoriginal.jpg"), :rel => 'fancybox-thumb2', :class =>"fancybox-thumb" %>
      <%= link_to image_tag("1bedroomoriginals/1brfloorplanoriginal.jpg", :class => 'bedroom-thumbs'), image_path("1bedroomoriginals/1brfloorplanoriginal.jpg"), :rel => 'fancybox-thumb2', :class =>"fancybox-thumb" %>
      <%= link_to image_tag("1bedroomoriginals/1brfloorplanoriginal.jpg", :class => 'bedroom-thumbs'), image_path("1bedroomoriginals/1brfloorplanoriginal.jpg"), :rel => 'fancybox-thumb2', :class =>"fancybox-thumb" %>
      <%= link_to image_tag("1bedroomoriginals/1brfloorplanoriginal.jpg", :class => 'bedroom-thumbs'), image_path("1bedroomoriginals/1brfloorplanoriginal.jpg"), :rel => 'fancybox-thumb2', :class =>"fancybox-thumb" %> 
    </div>
  </div>
</div>

app/views/cherrystreet/index.html.erb
<!-- start of carousel -->
<div id="cherry-street-carousel" class="carousel slide col-xs-12" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="cherry-street-carousel" data-slide-to="0" class="active"></li>
      <li data-target="cherry-street-carousel" data-slide-to="1"></li>
      <li data-target="cherry-street-carousel" data-slide-to="2"></li>
    </ol>
    <!-- Wrapper for slides -->
      <div class="carousel-inner">
        <div class="item active">
          <%= image_tag("philly1.jpg", :alt => "PHILLY1", :class =>"img-responsive carousel-pics") %>
          <div class="carousel-caption">
          </div>
        </div>
        <div class="item">
          <%= image_tag("philly2.jpg", :alt => "PHILLY2", :class =>"img-responsive carousel-pics") %>
          <div class="carousel-caption">
          </div>
        </div>
        <div class="item">
          <%= image_tag("philly3.jpg", :alt => "PHILLY3", :class =>"img-responsive carousel-pics") %>
          <div class="carousel-caption">
          </div>
        </div>
      </div>
    <!-- Controls -->
    <a class="left carousel-control" href="#cherry-street-carousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#cherry-street-carousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>
    <!-- end of carousel -->

<!-- start of 3 marketing points -->
  <div class="row homepage-marketing-padding">
    <div class="col-xs-4">
      <h2 class="homepage-marketing">About Cherry Street</h2>
      <p class="marketing-indent">Located in the heart of Philadelphia, Cherry Street Apartments are just steps away from Center City and Chinatown. </p>
    </div>
    <div class="col-xs-4">
      <h2 class="homepage-marketing">Newly Constructed</h2>
      <p class="marketing-indent">Our apartments were finished in 2014. They are are modern, sleek, and ready for you to outfit with your personality and sense of style. Come in for a viewing today!</p>
    </div>
    <div class="col-xs-4">
      <h2 class="homepage-marketing"><%= link_to "Neighborhood", cherrystreet_neighborhood_path %></h2>

      <p class="marketing-indent">Cherry street is located . SEPTA buses, restaurants, groceries are all within walking distance.</p>
    </div>
<!-- End of 3 marketing points -->
  </div>

app/views/comments/_comment.html.erb
<%= content_tag :div, id:"comment-#{comment.id}" do %>
  <div class="panel panel-default">
    <div class="panel panel-body" style="margin-bottom:0px;padding:5px;">
      <small>
        <% if comment.user.role == 'admin' %>
          <span class="label label-primary">Admin</span>
        <% else %>
          <span class="label label-default">Tenant</span>
        <% end %>
        <strong><%= comment.user.first_name %> <%= comment.user.last_name %></strong> commented <%= time_ago_in_words(comment.created_at) %> ago
        <% if can? :destroy, comment %>
          | <%= link_to "Delete", comment_url_helper(comment), method: :delete, remote: true %>
        <% end %>
      </small>
      <p><%= comment.comment %></p>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<%= form_for [mr, comment] do |f| %>
  <% if comment.errors.any? %>
    <div class="alert alert-block">
      <ul>
        <% comment.errors.full_message.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= control_group_tag(comment.errors[:comment]) do %>
    <%= f.text_area :comment, class: "form-control" %>
  <% end %>
  <%= f.submit "Add Comment", class: 'btn btn-primary btn-xs', style: 'margin-top: 10px'  %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Logo</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Home", root_url %></li></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Contact Us", contact_path %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Buildings<span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Cherry Street", cherrystreet_index_path %></li>
            <li><%= link_to "Other Building", "#" %></li>
          </ul>
        </li>
        <% if current_user %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Hello <%= current_user.first_name %>!<span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Maintenance Requests", maintenance_requests_path %></li>
            <% if current_user.role == "admin" %>
              <li><%= link_to "Admin View", '/admin/' %></li>
            <% end %>
            <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %><li>  
          </li>
        <% else %>
          <li><%= link_to "Sign In", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE HTML>
<html>

<head>
  <title>Philadelphia Rentals</title>
  <script type="text/javascript" src="http://code.jquery.com/jquery-latest.min.js"></script>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <%= render 'layouts/navbar'  %>
    <div class="panel panel-default">
      
    <% if controller.controller_name == "cherrystreet" %>
      <%= render 'cherrystreet/navbar'  %>
    <% end %>
    
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:error] %>
        <div class="alert alert-danger">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:error] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% elsif flash[:not_approved] %>
        <div class="alert alert">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:not_approved] %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/maintenance_requests/edit.html.erb
<div class="panel-heading">
  <h3 class="panel-title">Edit Maintenance Request</h3>
</div>

<div class="panel-body">
  <%= render partial: 'form', locals: { mr: @mr } %>
</div>

app/views/maintenance_requests/index.html.erb
<div class="panel-heading">
  <h3 class="panel-title">Maintenance Requests</h3>
</div>
<div class="panel-body">
  <div class="row">
    <div class="col-md-offset-1 col-md-10">
      <div class="menu">
        <div class="btn-toolbar" role="toolbar">
          <div class="btn-group btn-group-xs">
            <%= link_to '<button type="button" class="btn btn-default btn-xs">All</button>'.html_safe, action: "index" %>
            <%= link_to '<button type="button" class="btn btn-danger btn-xs">Open</button>'.html_safe, action: "index", status: "Open" %>
            <%= link_to '<button type="button" class="btn btn-success btn-xs">Closed</button>'.html_safe, action: "index", status: "Closed" %>
          </div>
          <div class="btn-group" style="float:right;">
            <%= link_to new_maintenance_request_path, class: 'btn btn-default btn-xs' do %>
              <i class="glyphicon glyphicon-pencil"></i>&nbsp; New
            <% end %>
          </div>
        </div>
      </div>

      <br>

      <% if @mainrequests %>
        <% @mainrequests.each do |mr| %>
          <div class="panel panel-default">
            <div class="panel-heading">
              <h4 class="panel-title">
                <% if mr.status == "Open" %>
                  <span class="label label-danger">Open</span>
                <% else %>
                  <span class="label label-success">Closed</span>
                <% end %>
                <% if mr.apartment %>
                  <strong><%= mr.apartment.building.name %> | <%= mr.apartment.unit %></strong>:
                <% end %>
                &nbsp;<%= link_to mr.title, maintenance_request_path(mr) %>
              </h4>
            </div>
            <div class="panel-body">
              <strong>Opened: </strong> <%= mr.created_at.strftime("%m/%d/%Y") %> <br>        
              <strong>Priority: </strong> <%= mr.priority %> <br>
              <strong>Description: </strong> <br>
              <div class="well well-sm"><%= mr.description %></div>
              <%= link_to maintenance_request_path(mr) do %>
                <span class="badge"><%= mr.maintenance_comments.count %>&nbsp; Comments</span>
              <% end %>
            </div>
          </div>
        <% end %>
      <% else %>
        <p>To add a maintenance request, please click <%= link_to "here", new_maintenance_request_path %>.</p>
      <% end %>
      <% if @mainrequests %>
        <div class="center">
          <%= will_paginate @mainrequests, renderer: BootstrapPagination::Rails %>    
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/maintenance_requests/new.html.erb
<div class="panel-heading">
  <h3 class="panel-title">Create a Maintenance Request</h3>
</div>

<div class="panel-body">
  <%= render partial: 'form', locals: { mr: @mr } %>
</div>

app/views/maintenance_requests/show.html.erb
<div class="panel-body">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title" style="overflow:hidden;">
        <div class="title" style="float:left;">
          <% if @mr.status == "Open" %>
            <span class="label label-danger">Open</span>
          <% else %>
            <span class="label label-success">Closed</span>
          <% end %>
          <% if @mr.apartment %>
            <strong><%= @mr.apartment.building.name %> | <%= @mr.apartment.unit %></strong>: 
          <% end %>
        </div>
        &nbsp; <%= @mr.title %>
        <div class="title" style="float:right;">
          <%= link_to edit_maintenance_request_path(@mr), class: 'btn btn-default btn-xs' do %>
            <i class="glyphicon glyphicon-edit"></i>&nbsp; Edit
          <% end %>
        </div>
      </h3>
    </div>
    <div class="panel-body">
      <strong>Created by: </strong> <%= @mr.user.first_name %> <%= @mr.user.last_name %> <br>
      <strong>Opened: </strong> <%= @mr.created_at.strftime("%m/%d/%Y") %> <br>        
      <strong>Priority: </strong> <%= @mr.priority %> <br>
      <strong>Description: </strong> <br>
      <div class="well well-sm"><%= @mr.description %></div>
      <span class="badge"><%= @mr.maintenance_comments.count %>&nbsp; Comments</span>
    </div>
  </div>
  <h4>New Comment</h4>
  <%= render partial: 'comments/form', locals: {mr: @mr, comment: @comment} %>
  <br>
  <div class="comments">
    <%= render partial: 'comments/comment', collection: @comments %>
  </div>
</div>

app/views/welcome/contact.html.erb
<!-- start of building images -->
<div class="row row-padding">
  <div class="col-xs-8">
    <h1>Contact Us!</h1>
    <p>Interested in setting up a viewing?</p>
    <p>Fill out the form below and one of our representatives will get right to you</p>
  </div>
</div>

app/views/welcome/index.html.erb
<!-- start of building images -->
<div class="col-xs-12">
  <h1 class="homepage-marketing">Welcome to Cherry & Ridge Apartments!</h1>
</div>
<div class="panel-body">
  <div class="row">
    <div class="col-xs-4 imgwrap col-xs-offset-2">
      <%= link_to image_tag("homepage_cherrystreet.jpg", :class=> "building-image"), "cherrystreet" %>
      <p><%= link_to "908 Cherry Street", "cherrystreet", :class=> "imgDescription linkhover" %> </p>
    </div>
    <div class="col-xs-4 imgwrap">
      <%= link_to image_tag("homepage_otherbuilding.jpg", :class=> "building-image"), "#" %>
      <p><%= link_to "913 Ridge Street", "cherrystreet", :class=> "imgDescription linkhover" %> </p>
    </div>
  </div>
</div>
<!-- start of 3 marketing points -->
<div class="row homepage-marketing-padding">
  <div class="col-xs-4">
    <h1 class="homepage-marketing">About Us!!!!!</h1>
    <p class="marketing-indent">We have 500 combined years of real estate experience and are here to make sure you get up on the right side of the bed!</p>
  </div>
  <div class="col-xs-4">
    <h1 class="homepage-marketing"><%= link_to "Contact", contact_path %></h1>
    <p class="marketing-indent">Have a question? Want to give us a compliment? Give us a call at (911) 911-9111!</p>
  </div>
  <div class="col-xs-4">
    <h1 class="homepage-marketing">Have an issue?</h1>
    <p class="marketing-indent">Please stand by. Our online maintenance reporting will be online...eventually.</p>
  </div>
<!-- End of 3 marketing points -->
</div>